# Generated by Django 5.2.8 on 2025-11-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_dog_view_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите кличку собаки",
                        max_length=255,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "year_born",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Укажите год рождения",
                        null=True,
                        verbose_name="Год рождения",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите породу собаки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parents_dog",
                        to="dogs.breed",
                        verbose_name="порода",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parents",
                        to="dogs.dog",
                        verbose_name="Собака",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предок",
                "verbose_name_plural": "Предки",
            },
        ),
    ]
