# Generated by Django 5.2.8 on 2025-11-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_dog_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dog",
            options={
                "ordering": ["breed", "name"],
                "permissions": [
                    ("can_edit_breed", "Может менять породу"),
                    ("can_edit_description", "Может менять описание"),
                ],
                "verbose_name": "Собака",
                "verbose_name_plural": "Собаки",
            },
        ),
        migrations.AddField(
            model_name="dog",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
